version: 2.1

jobs: 
  build:
    machine: 
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run: docker build -t orchestracities/quantumleap .
  test_reporter:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          command: |
            pip install pipenv
            pipenv install --dev
      - run:
          command: |
              sudo sysctl -w vm.max_map_count=262144
              export PIPENV_SHELL=no
              source setup_dev_env.sh
              export tests=reporter
              pipenv run sh -c 'printenv'

workflows:
  main:
    jobs:
      - build
      - test_reporter:
          requires:
            - build
